/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stocks_laboratory.alphavantage2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseTopicsEntryItem
 */

public class ResponseTopicsEntryItem {
  @JsonProperty("topic")
  private String topic = null;

  @JsonProperty("relevance_score")
  private String relevance_score = null;

  public ResponseTopicsEntryItem topic(String topic) {
    this.topic = topic;
    return this;
  }

   /**
   * Get topic
   * @return topic
  **/
  public String getTopic() {
    return topic;
  }

  public void setTopic(String topic) {
    this.topic = topic;
  }

  public ResponseTopicsEntryItem relevance_score(String relevance_score) {
    this.relevance_score = relevance_score;
    return this;
  }

   /**
   * Get relevance_score
   * @return relevance_score
  **/
  public String getRelevanceScore() {
    return relevance_score;
  }

  public void setRelevanceScore(String relevance_score) {
    this.relevance_score = relevance_score;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseTopicsEntryItem Response_topicsEntryItem = (ResponseTopicsEntryItem) o;
    return Objects.equals(this.topic, Response_topicsEntryItem.topic) &&
        Objects.equals(this.relevance_score, Response_topicsEntryItem.relevance_score);
  }

  @Override
  public int hashCode() {
    return Objects.hash(topic, relevance_score);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseTopicsEntryItem {\n");
    
    sb.append("    topic: ").append(toIndentedString(topic)).append("\n");
    sb.append("    relevance_score: ").append(toIndentedString(relevance_score)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
