/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stocks_laboratory.twelvedata6.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseValuesEntryItem
 */

public class ResponseValuesEntryItem {
  @JsonProperty("volume")
  private String volume = null;

  @JsonProperty("datetime")
  private String datetime = null;

  @JsonProperty("high")
  private String high = null;

  @JsonProperty("low")
  private String low = null;

  @JsonProperty("close")
  private String close = null;

  @JsonProperty("open")
  private String open = null;

  public ResponseValuesEntryItem volume(String volume) {
    this.volume = volume;
    return this;
  }

   /**
   * Get volume
   * @return volume
  **/
  public String getVolume() {
    return volume;
  }

  public void setVolume(String volume) {
    this.volume = volume;
  }

  public ResponseValuesEntryItem datetime(String datetime) {
    this.datetime = datetime;
    return this;
  }

   /**
   * Get datetime
   * @return datetime
  **/
  public String getDatetime() {
    return datetime;
  }

  public void setDatetime(String datetime) {
    this.datetime = datetime;
  }

  public ResponseValuesEntryItem high(String high) {
    this.high = high;
    return this;
  }

   /**
   * Get high
   * @return high
  **/
  public String getHigh() {
    return high;
  }

  public void setHigh(String high) {
    this.high = high;
  }

  public ResponseValuesEntryItem low(String low) {
    this.low = low;
    return this;
  }

   /**
   * Get low
   * @return low
  **/
  public String getLow() {
    return low;
  }

  public void setLow(String low) {
    this.low = low;
  }

  public ResponseValuesEntryItem close(String close) {
    this.close = close;
    return this;
  }

   /**
   * Get close
   * @return close
  **/
  public String getClose() {
    return close;
  }

  public void setClose(String close) {
    this.close = close;
  }

  public ResponseValuesEntryItem open(String open) {
    this.open = open;
    return this;
  }

   /**
   * Get open
   * @return open
  **/
  public String getOpen() {
    return open;
  }

  public void setOpen(String open) {
    this.open = open;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseValuesEntryItem Response_valuesEntryItem = (ResponseValuesEntryItem) o;
    return Objects.equals(this.volume, Response_valuesEntryItem.volume) &&
        Objects.equals(this.datetime, Response_valuesEntryItem.datetime) &&
        Objects.equals(this.high, Response_valuesEntryItem.high) &&
        Objects.equals(this.low, Response_valuesEntryItem.low) &&
        Objects.equals(this.close, Response_valuesEntryItem.close) &&
        Objects.equals(this.open, Response_valuesEntryItem.open);
  }

  @Override
  public int hashCode() {
    return Objects.hash(volume, datetime, high, low, close, open);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseValuesEntryItem {\n");
    
    sb.append("    volume: ").append(toIndentedString(volume)).append("\n");
    sb.append("    datetime: ").append(toIndentedString(datetime)).append("\n");
    sb.append("    high: ").append(toIndentedString(high)).append("\n");
    sb.append("    low: ").append(toIndentedString(low)).append("\n");
    sb.append("    close: ").append(toIndentedString(close)).append("\n");
    sb.append("    open: ").append(toIndentedString(open)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
