/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stocks_laboratory.twelvedata6.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseMeta
 */

public class ResponseMeta {
  @JsonProperty("exchange_timezone")
  private String exchange_timezone = null;

  @JsonProperty("symbol")
  private String symbol = null;

  @JsonProperty("mic_code")
  private String mic_code = null;

  @JsonProperty("interval")
  private String interval = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("exchange")
  private String exchange = null;

  @JsonProperty("type")
  private String type = null;

  public ResponseMeta exchange_timezone(String exchange_timezone) {
    this.exchange_timezone = exchange_timezone;
    return this;
  }

   /**
   * Get exchange_timezone
   * @return exchange_timezone
  **/
  public String getExchangeTimezone() {
    return exchange_timezone;
  }

  public void setExchangeTimezone(String exchange_timezone) {
    this.exchange_timezone = exchange_timezone;
  }

  public ResponseMeta symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public ResponseMeta mic_code(String mic_code) {
    this.mic_code = mic_code;
    return this;
  }

   /**
   * Get mic_code
   * @return mic_code
  **/
  public String getMicCode() {
    return mic_code;
  }

  public void setMicCode(String mic_code) {
    this.mic_code = mic_code;
  }

  public ResponseMeta interval(String interval) {
    this.interval = interval;
    return this;
  }

   /**
   * Get interval
   * @return interval
  **/
  public String getInterval() {
    return interval;
  }

  public void setInterval(String interval) {
    this.interval = interval;
  }

  public ResponseMeta currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public ResponseMeta exchange(String exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Get exchange
   * @return exchange
  **/
  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public ResponseMeta type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseMeta Response_meta = (ResponseMeta) o;
    return Objects.equals(this.exchange_timezone, Response_meta.exchange_timezone) &&
        Objects.equals(this.symbol, Response_meta.symbol) &&
        Objects.equals(this.mic_code, Response_meta.mic_code) &&
        Objects.equals(this.interval, Response_meta.interval) &&
        Objects.equals(this.currency, Response_meta.currency) &&
        Objects.equals(this.exchange, Response_meta.exchange) &&
        Objects.equals(this.type, Response_meta.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(exchange_timezone, symbol, mic_code, interval, currency, exchange, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseMeta {\n");
    
    sb.append("    exchange_timezone: ").append(toIndentedString(exchange_timezone)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    mic_code: ").append(toIndentedString(mic_code)).append("\n");
    sb.append("    interval: ").append(toIndentedString(interval)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
