/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stocks_laboratory.twelvedata6.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stocks_laboratory.twelvedata6.model.ResponseMeta;
import com.stocks_laboratory.twelvedata6.model.ResponseValuesEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("meta")
  private ResponseMeta meta = null;

  @JsonProperty("values")
  private List<ResponseValuesEntryItem> values = new ArrayList<>();

  @JsonProperty("status")
  private String status = null;

  public RootResponse meta(ResponseMeta meta) {
    this.meta = meta;
    return this;
  }

   /**
   * Get meta
   * @return meta
  **/
  public ResponseMeta getMeta() {
    return meta;
  }

  public void setMeta(ResponseMeta meta) {
    this.meta = meta;
  }

  public RootResponse values(List<ResponseValuesEntryItem> values) {
    this.values = values;
    return this;
  }

  public RootResponse addValuesItem(ResponseValuesEntryItem valuesItem) {
    this.values.add(valuesItem);
    return this;
  }

   /**
   * Get values
   * @return values
  **/
  public List<ResponseValuesEntryItem> getValues() {
    return values;
  }

  public void setValues(List<ResponseValuesEntryItem> values) {
    this.values = values;
  }

  public RootResponse status(String status) {
    this.status = status;
    return this;
  }

   /**
   * Get status
   * @return status
  **/
  public String getStatus() {
    return status;
  }

  public void setStatus(String status) {
    this.status = status;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.meta, RootResponse.meta) &&
        Objects.equals(this.values, RootResponse.values) &&
        Objects.equals(this.status, RootResponse.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(meta, values, status);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    values: ").append(toIndentedString(values)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
