/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stocks_laboratory.twelvedata7.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stocks_laboratory.twelvedata7.model.ResponseAAPL;
import com.stocks_laboratory.twelvedata7.model.ResponseGOOGL;
import com.stocks_laboratory.twelvedata7.model.ResponseMSFT;
import com.stocks_laboratory.twelvedata7.model.ResponseTSLA;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("MSFT")
  private ResponseMSFT MSFT = null;

  @JsonProperty("GOOGL")
  private ResponseGOOGL GOOGL = null;

  @JsonProperty("AAPL")
  private ResponseAAPL AAPL = null;

  @JsonProperty("TSLA")
  private ResponseTSLA TSLA = null;

  public RootResponse MSFT(ResponseMSFT MSFT) {
    this.MSFT = MSFT;
    return this;
  }

   /**
   * Get MSFT
   * @return MSFT
  **/
  public ResponseMSFT getMSFT() {
    return MSFT;
  }

  public void setMSFT(ResponseMSFT MSFT) {
    this.MSFT = MSFT;
  }

  public RootResponse GOOGL(ResponseGOOGL GOOGL) {
    this.GOOGL = GOOGL;
    return this;
  }

   /**
   * Get GOOGL
   * @return GOOGL
  **/
  public ResponseGOOGL getGOOGL() {
    return GOOGL;
  }

  public void setGOOGL(ResponseGOOGL GOOGL) {
    this.GOOGL = GOOGL;
  }

  public RootResponse AAPL(ResponseAAPL AAPL) {
    this.AAPL = AAPL;
    return this;
  }

   /**
   * Get AAPL
   * @return AAPL
  **/
  public ResponseAAPL getAAPL() {
    return AAPL;
  }

  public void setAAPL(ResponseAAPL AAPL) {
    this.AAPL = AAPL;
  }

  public RootResponse TSLA(ResponseTSLA TSLA) {
    this.TSLA = TSLA;
    return this;
  }

   /**
   * Get TSLA
   * @return TSLA
  **/
  public ResponseTSLA getTSLA() {
    return TSLA;
  }

  public void setTSLA(ResponseTSLA TSLA) {
    this.TSLA = TSLA;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.MSFT, RootResponse.MSFT) &&
        Objects.equals(this.GOOGL, RootResponse.GOOGL) &&
        Objects.equals(this.AAPL, RootResponse.AAPL) &&
        Objects.equals(this.TSLA, RootResponse.TSLA);
  }

  @Override
  public int hashCode() {
    return Objects.hash(MSFT, GOOGL, AAPL, TSLA);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    MSFT: ").append(toIndentedString(MSFT)).append("\n");
    sb.append("    GOOGL: ").append(toIndentedString(GOOGL)).append("\n");
    sb.append("    AAPL: ").append(toIndentedString(AAPL)).append("\n");
    sb.append("    TSLA: ").append(toIndentedString(TSLA)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
