/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stocks_laboratory.Nifty100Stocks.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
import com.stocks_laboratory.Nifty100Stocks.model.ResponseRootResponseROOTEntryItem;
import java.util.ArrayList;
import java.util.List;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("RootResponseROOT")
  private List<ResponseRootResponseROOTEntryItem> RootResponseROOT = new ArrayList<>();

  public RootResponse RootResponseROOT(List<ResponseRootResponseROOTEntryItem> RootResponseROOT) {
    this.RootResponseROOT = RootResponseROOT;
    return this;
  }

  public RootResponse addRootResponseROOTItem(ResponseRootResponseROOTEntryItem RootResponseROOTItem) {
    this.RootResponseROOT.add(RootResponseROOTItem);
    return this;
  }

   /**
   * Get RootResponseROOT
   * @return RootResponseROOT
  **/
  public List<ResponseRootResponseROOTEntryItem> getRootResponseROOT() {
    return RootResponseROOT;
  }

  public void setRootResponseROOT(List<ResponseRootResponseROOTEntryItem> RootResponseROOT) {
    this.RootResponseROOT = RootResponseROOT;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.RootResponseROOT, RootResponse.RootResponseROOT);
  }

  @Override
  public int hashCode() {
    return Objects.hash(RootResponseROOT);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    RootResponseROOT: ").append(toIndentedString(RootResponseROOT)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
