/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stocks_laboratory.Nifty50Stocks.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseRootResponseROOTEntryItem
 */

public class ResponseRootResponseROOTEntryItem {
  @JsonProperty("yearLow")
  private Integer yearLow = null;

  @JsonProperty("symbol")
  private String symbol = null;

  @JsonProperty("identifier")
  private String identifier = null;

  @JsonProperty("totalTradedVolume")
  private Integer totalTradedVolume = null;

  @JsonProperty("change")
  private Double change = null;

  @JsonProperty("dayLow")
  private Double dayLow = null;

  @JsonProperty("perChange30d")
  private Double perChange30d = null;

  @JsonProperty("yearHigh")
  private Integer yearHigh = null;

  @JsonProperty("perChange365d")
  private Double perChange365d = null;

  @JsonProperty("previousClose")
  private Double previousClose = null;

  @JsonProperty("pChange")
  private Double pChange = null;

  @JsonProperty("totalTradedValue")
  private Double totalTradedValue = null;

  @JsonProperty("open")
  private Double open = null;

  @JsonProperty("dayHigh")
  private Double dayHigh = null;

  @JsonProperty("lastPrice")
  private Double lastPrice = null;

  @JsonProperty("lastUpdateTime")
  private String lastUpdateTime = null;

  public ResponseRootResponseROOTEntryItem yearLow(Integer yearLow) {
    this.yearLow = yearLow;
    return this;
  }

   /**
   * Get yearLow
   * @return yearLow
  **/
  public Integer getYearLow() {
    return yearLow;
  }

  public void setYearLow(Integer yearLow) {
    this.yearLow = yearLow;
  }

  public ResponseRootResponseROOTEntryItem symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public ResponseRootResponseROOTEntryItem identifier(String identifier) {
    this.identifier = identifier;
    return this;
  }

   /**
   * Get identifier
   * @return identifier
  **/
  public String getIdentifier() {
    return identifier;
  }

  public void setIdentifier(String identifier) {
    this.identifier = identifier;
  }

  public ResponseRootResponseROOTEntryItem totalTradedVolume(Integer totalTradedVolume) {
    this.totalTradedVolume = totalTradedVolume;
    return this;
  }

   /**
   * Get totalTradedVolume
   * @return totalTradedVolume
  **/
  public Integer getTotalTradedVolume() {
    return totalTradedVolume;
  }

  public void setTotalTradedVolume(Integer totalTradedVolume) {
    this.totalTradedVolume = totalTradedVolume;
  }

  public ResponseRootResponseROOTEntryItem change(Double change) {
    this.change = change;
    return this;
  }

   /**
   * Get change
   * @return change
  **/
  public Double getChange() {
    return change;
  }

  public void setChange(Double change) {
    this.change = change;
  }

  public ResponseRootResponseROOTEntryItem dayLow(Double dayLow) {
    this.dayLow = dayLow;
    return this;
  }

   /**
   * Get dayLow
   * @return dayLow
  **/
  public Double getDayLow() {
    return dayLow;
  }

  public void setDayLow(Double dayLow) {
    this.dayLow = dayLow;
  }

  public ResponseRootResponseROOTEntryItem perChange30d(Double perChange30d) {
    this.perChange30d = perChange30d;
    return this;
  }

   /**
   * Get perChange30d
   * @return perChange30d
  **/
  public Double getPerChange30d() {
    return perChange30d;
  }

  public void setPerChange30d(Double perChange30d) {
    this.perChange30d = perChange30d;
  }

  public ResponseRootResponseROOTEntryItem yearHigh(Integer yearHigh) {
    this.yearHigh = yearHigh;
    return this;
  }

   /**
   * Get yearHigh
   * @return yearHigh
  **/
  public Integer getYearHigh() {
    return yearHigh;
  }

  public void setYearHigh(Integer yearHigh) {
    this.yearHigh = yearHigh;
  }

  public ResponseRootResponseROOTEntryItem perChange365d(Double perChange365d) {
    this.perChange365d = perChange365d;
    return this;
  }

   /**
   * Get perChange365d
   * @return perChange365d
  **/
  public Double getPerChange365d() {
    return perChange365d;
  }

  public void setPerChange365d(Double perChange365d) {
    this.perChange365d = perChange365d;
  }

  public ResponseRootResponseROOTEntryItem previousClose(Double previousClose) {
    this.previousClose = previousClose;
    return this;
  }

   /**
   * Get previousClose
   * @return previousClose
  **/
  public Double getPreviousClose() {
    return previousClose;
  }

  public void setPreviousClose(Double previousClose) {
    this.previousClose = previousClose;
  }

  public ResponseRootResponseROOTEntryItem pChange(Double pChange) {
    this.pChange = pChange;
    return this;
  }

   /**
   * Get pChange
   * @return pChange
  **/
  public Double getPChange() {
    return pChange;
  }

  public void setPChange(Double pChange) {
    this.pChange = pChange;
  }

  public ResponseRootResponseROOTEntryItem totalTradedValue(Double totalTradedValue) {
    this.totalTradedValue = totalTradedValue;
    return this;
  }

   /**
   * Get totalTradedValue
   * @return totalTradedValue
  **/
  public Double getTotalTradedValue() {
    return totalTradedValue;
  }

  public void setTotalTradedValue(Double totalTradedValue) {
    this.totalTradedValue = totalTradedValue;
  }

  public ResponseRootResponseROOTEntryItem open(Double open) {
    this.open = open;
    return this;
  }

   /**
   * Get open
   * @return open
  **/
  public Double getOpen() {
    return open;
  }

  public void setOpen(Double open) {
    this.open = open;
  }

  public ResponseRootResponseROOTEntryItem dayHigh(Double dayHigh) {
    this.dayHigh = dayHigh;
    return this;
  }

   /**
   * Get dayHigh
   * @return dayHigh
  **/
  public Double getDayHigh() {
    return dayHigh;
  }

  public void setDayHigh(Double dayHigh) {
    this.dayHigh = dayHigh;
  }

  public ResponseRootResponseROOTEntryItem lastPrice(Double lastPrice) {
    this.lastPrice = lastPrice;
    return this;
  }

   /**
   * Get lastPrice
   * @return lastPrice
  **/
  public Double getLastPrice() {
    return lastPrice;
  }

  public void setLastPrice(Double lastPrice) {
    this.lastPrice = lastPrice;
  }

  public ResponseRootResponseROOTEntryItem lastUpdateTime(String lastUpdateTime) {
    this.lastUpdateTime = lastUpdateTime;
    return this;
  }

   /**
   * Get lastUpdateTime
   * @return lastUpdateTime
  **/
  public String getLastUpdateTime() {
    return lastUpdateTime;
  }

  public void setLastUpdateTime(String lastUpdateTime) {
    this.lastUpdateTime = lastUpdateTime;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseRootResponseROOTEntryItem Response_RootResponseROOTEntryItem = (ResponseRootResponseROOTEntryItem) o;
    return Objects.equals(this.yearLow, Response_RootResponseROOTEntryItem.yearLow) &&
        Objects.equals(this.symbol, Response_RootResponseROOTEntryItem.symbol) &&
        Objects.equals(this.identifier, Response_RootResponseROOTEntryItem.identifier) &&
        Objects.equals(this.totalTradedVolume, Response_RootResponseROOTEntryItem.totalTradedVolume) &&
        Objects.equals(this.change, Response_RootResponseROOTEntryItem.change) &&
        Objects.equals(this.dayLow, Response_RootResponseROOTEntryItem.dayLow) &&
        Objects.equals(this.perChange30d, Response_RootResponseROOTEntryItem.perChange30d) &&
        Objects.equals(this.yearHigh, Response_RootResponseROOTEntryItem.yearHigh) &&
        Objects.equals(this.perChange365d, Response_RootResponseROOTEntryItem.perChange365d) &&
        Objects.equals(this.previousClose, Response_RootResponseROOTEntryItem.previousClose) &&
        Objects.equals(this.pChange, Response_RootResponseROOTEntryItem.pChange) &&
        Objects.equals(this.totalTradedValue, Response_RootResponseROOTEntryItem.totalTradedValue) &&
        Objects.equals(this.open, Response_RootResponseROOTEntryItem.open) &&
        Objects.equals(this.dayHigh, Response_RootResponseROOTEntryItem.dayHigh) &&
        Objects.equals(this.lastPrice, Response_RootResponseROOTEntryItem.lastPrice) &&
        Objects.equals(this.lastUpdateTime, Response_RootResponseROOTEntryItem.lastUpdateTime);
  }

  @Override
  public int hashCode() {
    return Objects.hash(yearLow, symbol, identifier, totalTradedVolume, change, dayLow, perChange30d, yearHigh, perChange365d, previousClose, pChange, totalTradedValue, open, dayHigh, lastPrice, lastUpdateTime);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseRootResponseROOTEntryItem {\n");
    
    sb.append("    yearLow: ").append(toIndentedString(yearLow)).append("\n");
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    identifier: ").append(toIndentedString(identifier)).append("\n");
    sb.append("    totalTradedVolume: ").append(toIndentedString(totalTradedVolume)).append("\n");
    sb.append("    change: ").append(toIndentedString(change)).append("\n");
    sb.append("    dayLow: ").append(toIndentedString(dayLow)).append("\n");
    sb.append("    perChange30d: ").append(toIndentedString(perChange30d)).append("\n");
    sb.append("    yearHigh: ").append(toIndentedString(yearHigh)).append("\n");
    sb.append("    perChange365d: ").append(toIndentedString(perChange365d)).append("\n");
    sb.append("    previousClose: ").append(toIndentedString(previousClose)).append("\n");
    sb.append("    pChange: ").append(toIndentedString(pChange)).append("\n");
    sb.append("    totalTradedValue: ").append(toIndentedString(totalTradedValue)).append("\n");
    sb.append("    open: ").append(toIndentedString(open)).append("\n");
    sb.append("    dayHigh: ").append(toIndentedString(dayHigh)).append("\n");
    sb.append("    lastPrice: ").append(toIndentedString(lastPrice)).append("\n");
    sb.append("    lastUpdateTime: ").append(toIndentedString(lastUpdateTime)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
