/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stocks_laboratory.USDtoINR.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("new_amount")
  private Double new_amount = null;

  @JsonProperty("new_currency")
  private String new_currency = null;

  @JsonProperty("old_amount")
  private Integer old_amount = null;

  @JsonProperty("old_currency")
  private String old_currency = null;

  public RootResponse new_amount(Double new_amount) {
    this.new_amount = new_amount;
    return this;
  }

   /**
   * Get new_amount
   * @return new_amount
  **/
  public Double getNewAmount() {
    return new_amount;
  }

  public void setNewAmount(Double new_amount) {
    this.new_amount = new_amount;
  }

  public RootResponse new_currency(String new_currency) {
    this.new_currency = new_currency;
    return this;
  }

   /**
   * Get new_currency
   * @return new_currency
  **/
  public String getNewCurrency() {
    return new_currency;
  }

  public void setNewCurrency(String new_currency) {
    this.new_currency = new_currency;
  }

  public RootResponse old_amount(Integer old_amount) {
    this.old_amount = old_amount;
    return this;
  }

   /**
   * Get old_amount
   * @return old_amount
  **/
  public Integer getOldAmount() {
    return old_amount;
  }

  public void setOldAmount(Integer old_amount) {
    this.old_amount = old_amount;
  }

  public RootResponse old_currency(String old_currency) {
    this.old_currency = old_currency;
    return this;
  }

   /**
   * Get old_currency
   * @return old_currency
  **/
  public String getOldCurrency() {
    return old_currency;
  }

  public void setOldCurrency(String old_currency) {
    this.old_currency = old_currency;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.new_amount, RootResponse.new_amount) &&
        Objects.equals(this.new_currency, RootResponse.new_currency) &&
        Objects.equals(this.old_amount, RootResponse.old_amount) &&
        Objects.equals(this.old_currency, RootResponse.old_currency);
  }

  @Override
  public int hashCode() {
    return Objects.hash(new_amount, new_currency, old_amount, old_currency);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    new_amount: ").append(toIndentedString(new_amount)).append("\n");
    sb.append("    new_currency: ").append(toIndentedString(new_currency)).append("\n");
    sb.append("    old_amount: ").append(toIndentedString(old_amount)).append("\n");
    sb.append("    old_currency: ").append(toIndentedString(old_currency)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
