/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stocks_laboratory.alphavantage.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("Description")
  private String Description = null;

  @JsonProperty("Address")
  private String Address = null;

  @JsonProperty("200DayMovingAverage")
  private String _200DayMovingAverage = null;

  @JsonProperty("Symbol")
  private String Symbol = null;

  @JsonProperty("EBITDA")
  private String EBITDA = null;

  @JsonProperty("EPS")
  private String EPS = null;

  @JsonProperty("ExDividendDate")
  private String ExDividendDate = null;

  @JsonProperty("Name")
  private String Name = null;

  @JsonProperty("Beta")
  private String Beta = null;

  @JsonProperty("Industry")
  private String Industry = null;

  @JsonProperty("FiscalYearEnd")
  private String FiscalYearEnd = null;

  @JsonProperty("DividendYield")
  private String DividendYield = null;

  @JsonProperty("EVToEBITDA")
  private String evToEBITDA = null;

  @JsonProperty("AnalystTargetPrice")
  private String AnalystTargetPrice = null;

  @JsonProperty("Currency")
  private String Currency = null;

  @JsonProperty("DividendDate")
  private String DividendDate = null;

  @JsonProperty("PriceToSalesRatioTTM")
  private String PriceToSalesRatioTTM = null;

  @JsonProperty("EVToRevenue")
  private String evToRevenue = null;

  @JsonProperty("52WeekLow")
  private String _52WeekLow = null;

  @JsonProperty("GrossProfitTTM")
  private String GrossProfitTTM = null;

  @JsonProperty("DilutedEPSTTM")
  private String DilutedEPSTTM = null;

  @JsonProperty("QuarterlyEarningsGrowthYOY")
  private String QuarterlyEarningsGrowthYOY = null;

  @JsonProperty("CIK")
  private String CIK = null;

  @JsonProperty("OperatingMarginTTM")
  private String OperatingMarginTTM = null;

  @JsonProperty("ProfitMargin")
  private String ProfitMargin = null;

  @JsonProperty("Sector")
  private String Sector = null;

  @JsonProperty("ForwardPE")
  private String ForwardPE = null;

  @JsonProperty("LatestQuarter")
  private String LatestQuarter = null;

  @JsonProperty("TrailingPE")
  private String TrailingPE = null;

  @JsonProperty("RevenueTTM")
  private String RevenueTTM = null;

  @JsonProperty("DividendPerShare")
  private String DividendPerShare = null;

  @JsonProperty("RevenuePerShareTTM")
  private String RevenuePerShareTTM = null;

  @JsonProperty("QuarterlyRevenueGrowthYOY")
  private String QuarterlyRevenueGrowthYOY = null;

  @JsonProperty("ReturnOnAssetsTTM")
  private String ReturnOnAssetsTTM = null;

  @JsonProperty("Exchange")
  private String Exchange = null;

  @JsonProperty("AssetType")
  private String AssetType = null;

  @JsonProperty("BookValue")
  private String BookValue = null;

  @JsonProperty("PERatio")
  private String peRatio = null;

  @JsonProperty("PriceToBookRatio")
  private String PriceToBookRatio = null;

  @JsonProperty("SharesOutstanding")
  private String SharesOutstanding = null;

  @JsonProperty("Country")
  private String Country = null;

  @JsonProperty("MarketCapitalization")
  private String MarketCapitalization = null;

  @JsonProperty("PEGRatio")
  private String peGRatio = null;

  @JsonProperty("50DayMovingAverage")
  private String _50DayMovingAverage = null;

  @JsonProperty("52WeekHigh")
  private String _52WeekHigh = null;

  @JsonProperty("ReturnOnEquityTTM")
  private String ReturnOnEquityTTM = null;

  public RootResponse Description(String Description) {
    this.Description = Description;
    return this;
  }

   /**
   * Get Description
   * @return Description
  **/
  public String getDescription() {
    return Description;
  }

  public void setDescription(String Description) {
    this.Description = Description;
  }

  public RootResponse Address(String Address) {
    this.Address = Address;
    return this;
  }

   /**
   * Get Address
   * @return Address
  **/
  public String getAddress() {
    return Address;
  }

  public void setAddress(String Address) {
    this.Address = Address;
  }

  public RootResponse _200DayMovingAverage(String _200DayMovingAverage) {
    this._200DayMovingAverage = _200DayMovingAverage;
    return this;
  }

   /**
   * Get _200DayMovingAverage
   * @return _200DayMovingAverage
  **/
  public String get200DayMovingAverage() {
    return _200DayMovingAverage;
  }

  public void set200DayMovingAverage(String _200DayMovingAverage) {
    this._200DayMovingAverage = _200DayMovingAverage;
  }

  public RootResponse Symbol(String Symbol) {
    this.Symbol = Symbol;
    return this;
  }

   /**
   * Get Symbol
   * @return Symbol
  **/
  public String getSymbol() {
    return Symbol;
  }

  public void setSymbol(String Symbol) {
    this.Symbol = Symbol;
  }

  public RootResponse EBITDA(String EBITDA) {
    this.EBITDA = EBITDA;
    return this;
  }

   /**
   * Get EBITDA
   * @return EBITDA
  **/
  public String getEBITDA() {
    return EBITDA;
  }

  public void setEBITDA(String EBITDA) {
    this.EBITDA = EBITDA;
  }

  public RootResponse EPS(String EPS) {
    this.EPS = EPS;
    return this;
  }

   /**
   * Get EPS
   * @return EPS
  **/
  public String getEPS() {
    return EPS;
  }

  public void setEPS(String EPS) {
    this.EPS = EPS;
  }

  public RootResponse ExDividendDate(String ExDividendDate) {
    this.ExDividendDate = ExDividendDate;
    return this;
  }

   /**
   * Get ExDividendDate
   * @return ExDividendDate
  **/
  public String getExDividendDate() {
    return ExDividendDate;
  }

  public void setExDividendDate(String ExDividendDate) {
    this.ExDividendDate = ExDividendDate;
  }

  public RootResponse Name(String Name) {
    this.Name = Name;
    return this;
  }

   /**
   * Get Name
   * @return Name
  **/
  public String getName() {
    return Name;
  }

  public void setName(String Name) {
    this.Name = Name;
  }

  public RootResponse Beta(String Beta) {
    this.Beta = Beta;
    return this;
  }

   /**
   * Get Beta
   * @return Beta
  **/
  public String getBeta() {
    return Beta;
  }

  public void setBeta(String Beta) {
    this.Beta = Beta;
  }

  public RootResponse Industry(String Industry) {
    this.Industry = Industry;
    return this;
  }

   /**
   * Get Industry
   * @return Industry
  **/
  public String getIndustry() {
    return Industry;
  }

  public void setIndustry(String Industry) {
    this.Industry = Industry;
  }

  public RootResponse FiscalYearEnd(String FiscalYearEnd) {
    this.FiscalYearEnd = FiscalYearEnd;
    return this;
  }

   /**
   * Get FiscalYearEnd
   * @return FiscalYearEnd
  **/
  public String getFiscalYearEnd() {
    return FiscalYearEnd;
  }

  public void setFiscalYearEnd(String FiscalYearEnd) {
    this.FiscalYearEnd = FiscalYearEnd;
  }

  public RootResponse DividendYield(String DividendYield) {
    this.DividendYield = DividendYield;
    return this;
  }

   /**
   * Get DividendYield
   * @return DividendYield
  **/
  public String getDividendYield() {
    return DividendYield;
  }

  public void setDividendYield(String DividendYield) {
    this.DividendYield = DividendYield;
  }

  public RootResponse evToEBITDA(String evToEBITDA) {
    this.evToEBITDA = evToEBITDA;
    return this;
  }

   /**
   * Get evToEBITDA
   * @return evToEBITDA
  **/
  public String getEvToEBITDA() {
    return evToEBITDA;
  }

  public void setEvToEBITDA(String evToEBITDA) {
    this.evToEBITDA = evToEBITDA;
  }

  public RootResponse AnalystTargetPrice(String AnalystTargetPrice) {
    this.AnalystTargetPrice = AnalystTargetPrice;
    return this;
  }

   /**
   * Get AnalystTargetPrice
   * @return AnalystTargetPrice
  **/
  public String getAnalystTargetPrice() {
    return AnalystTargetPrice;
  }

  public void setAnalystTargetPrice(String AnalystTargetPrice) {
    this.AnalystTargetPrice = AnalystTargetPrice;
  }

  public RootResponse Currency(String Currency) {
    this.Currency = Currency;
    return this;
  }

   /**
   * Get Currency
   * @return Currency
  **/
  public String getCurrency() {
    return Currency;
  }

  public void setCurrency(String Currency) {
    this.Currency = Currency;
  }

  public RootResponse DividendDate(String DividendDate) {
    this.DividendDate = DividendDate;
    return this;
  }

   /**
   * Get DividendDate
   * @return DividendDate
  **/
  public String getDividendDate() {
    return DividendDate;
  }

  public void setDividendDate(String DividendDate) {
    this.DividendDate = DividendDate;
  }

  public RootResponse PriceToSalesRatioTTM(String PriceToSalesRatioTTM) {
    this.PriceToSalesRatioTTM = PriceToSalesRatioTTM;
    return this;
  }

   /**
   * Get PriceToSalesRatioTTM
   * @return PriceToSalesRatioTTM
  **/
  public String getPriceToSalesRatioTTM() {
    return PriceToSalesRatioTTM;
  }

  public void setPriceToSalesRatioTTM(String PriceToSalesRatioTTM) {
    this.PriceToSalesRatioTTM = PriceToSalesRatioTTM;
  }

  public RootResponse evToRevenue(String evToRevenue) {
    this.evToRevenue = evToRevenue;
    return this;
  }

   /**
   * Get evToRevenue
   * @return evToRevenue
  **/
  public String getEvToRevenue() {
    return evToRevenue;
  }

  public void setEvToRevenue(String evToRevenue) {
    this.evToRevenue = evToRevenue;
  }

  public RootResponse _52WeekLow(String _52WeekLow) {
    this._52WeekLow = _52WeekLow;
    return this;
  }

   /**
   * Get _52WeekLow
   * @return _52WeekLow
  **/
  public String get52WeekLow() {
    return _52WeekLow;
  }

  public void set52WeekLow(String _52WeekLow) {
    this._52WeekLow = _52WeekLow;
  }

  public RootResponse GrossProfitTTM(String GrossProfitTTM) {
    this.GrossProfitTTM = GrossProfitTTM;
    return this;
  }

   /**
   * Get GrossProfitTTM
   * @return GrossProfitTTM
  **/
  public String getGrossProfitTTM() {
    return GrossProfitTTM;
  }

  public void setGrossProfitTTM(String GrossProfitTTM) {
    this.GrossProfitTTM = GrossProfitTTM;
  }

  public RootResponse DilutedEPSTTM(String DilutedEPSTTM) {
    this.DilutedEPSTTM = DilutedEPSTTM;
    return this;
  }

   /**
   * Get DilutedEPSTTM
   * @return DilutedEPSTTM
  **/
  public String getDilutedEPSTTM() {
    return DilutedEPSTTM;
  }

  public void setDilutedEPSTTM(String DilutedEPSTTM) {
    this.DilutedEPSTTM = DilutedEPSTTM;
  }

  public RootResponse QuarterlyEarningsGrowthYOY(String QuarterlyEarningsGrowthYOY) {
    this.QuarterlyEarningsGrowthYOY = QuarterlyEarningsGrowthYOY;
    return this;
  }

   /**
   * Get QuarterlyEarningsGrowthYOY
   * @return QuarterlyEarningsGrowthYOY
  **/
  public String getQuarterlyEarningsGrowthYOY() {
    return QuarterlyEarningsGrowthYOY;
  }

  public void setQuarterlyEarningsGrowthYOY(String QuarterlyEarningsGrowthYOY) {
    this.QuarterlyEarningsGrowthYOY = QuarterlyEarningsGrowthYOY;
  }

  public RootResponse CIK(String CIK) {
    this.CIK = CIK;
    return this;
  }

   /**
   * Get CIK
   * @return CIK
  **/
  public String getCIK() {
    return CIK;
  }

  public void setCIK(String CIK) {
    this.CIK = CIK;
  }

  public RootResponse OperatingMarginTTM(String OperatingMarginTTM) {
    this.OperatingMarginTTM = OperatingMarginTTM;
    return this;
  }

   /**
   * Get OperatingMarginTTM
   * @return OperatingMarginTTM
  **/
  public String getOperatingMarginTTM() {
    return OperatingMarginTTM;
  }

  public void setOperatingMarginTTM(String OperatingMarginTTM) {
    this.OperatingMarginTTM = OperatingMarginTTM;
  }

  public RootResponse ProfitMargin(String ProfitMargin) {
    this.ProfitMargin = ProfitMargin;
    return this;
  }

   /**
   * Get ProfitMargin
   * @return ProfitMargin
  **/
  public String getProfitMargin() {
    return ProfitMargin;
  }

  public void setProfitMargin(String ProfitMargin) {
    this.ProfitMargin = ProfitMargin;
  }

  public RootResponse Sector(String Sector) {
    this.Sector = Sector;
    return this;
  }

   /**
   * Get Sector
   * @return Sector
  **/
  public String getSector() {
    return Sector;
  }

  public void setSector(String Sector) {
    this.Sector = Sector;
  }

  public RootResponse ForwardPE(String ForwardPE) {
    this.ForwardPE = ForwardPE;
    return this;
  }

   /**
   * Get ForwardPE
   * @return ForwardPE
  **/
  public String getForwardPE() {
    return ForwardPE;
  }

  public void setForwardPE(String ForwardPE) {
    this.ForwardPE = ForwardPE;
  }

  public RootResponse LatestQuarter(String LatestQuarter) {
    this.LatestQuarter = LatestQuarter;
    return this;
  }

   /**
   * Get LatestQuarter
   * @return LatestQuarter
  **/
  public String getLatestQuarter() {
    return LatestQuarter;
  }

  public void setLatestQuarter(String LatestQuarter) {
    this.LatestQuarter = LatestQuarter;
  }

  public RootResponse TrailingPE(String TrailingPE) {
    this.TrailingPE = TrailingPE;
    return this;
  }

   /**
   * Get TrailingPE
   * @return TrailingPE
  **/
  public String getTrailingPE() {
    return TrailingPE;
  }

  public void setTrailingPE(String TrailingPE) {
    this.TrailingPE = TrailingPE;
  }

  public RootResponse RevenueTTM(String RevenueTTM) {
    this.RevenueTTM = RevenueTTM;
    return this;
  }

   /**
   * Get RevenueTTM
   * @return RevenueTTM
  **/
  public String getRevenueTTM() {
    return RevenueTTM;
  }

  public void setRevenueTTM(String RevenueTTM) {
    this.RevenueTTM = RevenueTTM;
  }

  public RootResponse DividendPerShare(String DividendPerShare) {
    this.DividendPerShare = DividendPerShare;
    return this;
  }

   /**
   * Get DividendPerShare
   * @return DividendPerShare
  **/
  public String getDividendPerShare() {
    return DividendPerShare;
  }

  public void setDividendPerShare(String DividendPerShare) {
    this.DividendPerShare = DividendPerShare;
  }

  public RootResponse RevenuePerShareTTM(String RevenuePerShareTTM) {
    this.RevenuePerShareTTM = RevenuePerShareTTM;
    return this;
  }

   /**
   * Get RevenuePerShareTTM
   * @return RevenuePerShareTTM
  **/
  public String getRevenuePerShareTTM() {
    return RevenuePerShareTTM;
  }

  public void setRevenuePerShareTTM(String RevenuePerShareTTM) {
    this.RevenuePerShareTTM = RevenuePerShareTTM;
  }

  public RootResponse QuarterlyRevenueGrowthYOY(String QuarterlyRevenueGrowthYOY) {
    this.QuarterlyRevenueGrowthYOY = QuarterlyRevenueGrowthYOY;
    return this;
  }

   /**
   * Get QuarterlyRevenueGrowthYOY
   * @return QuarterlyRevenueGrowthYOY
  **/
  public String getQuarterlyRevenueGrowthYOY() {
    return QuarterlyRevenueGrowthYOY;
  }

  public void setQuarterlyRevenueGrowthYOY(String QuarterlyRevenueGrowthYOY) {
    this.QuarterlyRevenueGrowthYOY = QuarterlyRevenueGrowthYOY;
  }

  public RootResponse ReturnOnAssetsTTM(String ReturnOnAssetsTTM) {
    this.ReturnOnAssetsTTM = ReturnOnAssetsTTM;
    return this;
  }

   /**
   * Get ReturnOnAssetsTTM
   * @return ReturnOnAssetsTTM
  **/
  public String getReturnOnAssetsTTM() {
    return ReturnOnAssetsTTM;
  }

  public void setReturnOnAssetsTTM(String ReturnOnAssetsTTM) {
    this.ReturnOnAssetsTTM = ReturnOnAssetsTTM;
  }

  public RootResponse Exchange(String Exchange) {
    this.Exchange = Exchange;
    return this;
  }

   /**
   * Get Exchange
   * @return Exchange
  **/
  public String getExchange() {
    return Exchange;
  }

  public void setExchange(String Exchange) {
    this.Exchange = Exchange;
  }

  public RootResponse AssetType(String AssetType) {
    this.AssetType = AssetType;
    return this;
  }

   /**
   * Get AssetType
   * @return AssetType
  **/
  public String getAssetType() {
    return AssetType;
  }

  public void setAssetType(String AssetType) {
    this.AssetType = AssetType;
  }

  public RootResponse BookValue(String BookValue) {
    this.BookValue = BookValue;
    return this;
  }

   /**
   * Get BookValue
   * @return BookValue
  **/
  public String getBookValue() {
    return BookValue;
  }

  public void setBookValue(String BookValue) {
    this.BookValue = BookValue;
  }

  public RootResponse peRatio(String peRatio) {
    this.peRatio = peRatio;
    return this;
  }

   /**
   * Get peRatio
   * @return peRatio
  **/
  public String getPeRatio() {
    return peRatio;
  }

  public void setPeRatio(String peRatio) {
    this.peRatio = peRatio;
  }

  public RootResponse PriceToBookRatio(String PriceToBookRatio) {
    this.PriceToBookRatio = PriceToBookRatio;
    return this;
  }

   /**
   * Get PriceToBookRatio
   * @return PriceToBookRatio
  **/
  public String getPriceToBookRatio() {
    return PriceToBookRatio;
  }

  public void setPriceToBookRatio(String PriceToBookRatio) {
    this.PriceToBookRatio = PriceToBookRatio;
  }

  public RootResponse SharesOutstanding(String SharesOutstanding) {
    this.SharesOutstanding = SharesOutstanding;
    return this;
  }

   /**
   * Get SharesOutstanding
   * @return SharesOutstanding
  **/
  public String getSharesOutstanding() {
    return SharesOutstanding;
  }

  public void setSharesOutstanding(String SharesOutstanding) {
    this.SharesOutstanding = SharesOutstanding;
  }

  public RootResponse Country(String Country) {
    this.Country = Country;
    return this;
  }

   /**
   * Get Country
   * @return Country
  **/
  public String getCountry() {
    return Country;
  }

  public void setCountry(String Country) {
    this.Country = Country;
  }

  public RootResponse MarketCapitalization(String MarketCapitalization) {
    this.MarketCapitalization = MarketCapitalization;
    return this;
  }

   /**
   * Get MarketCapitalization
   * @return MarketCapitalization
  **/
  public String getMarketCapitalization() {
    return MarketCapitalization;
  }

  public void setMarketCapitalization(String MarketCapitalization) {
    this.MarketCapitalization = MarketCapitalization;
  }

  public RootResponse peGRatio(String peGRatio) {
    this.peGRatio = peGRatio;
    return this;
  }

   /**
   * Get peGRatio
   * @return peGRatio
  **/
  public String getPeGRatio() {
    return peGRatio;
  }

  public void setPeGRatio(String peGRatio) {
    this.peGRatio = peGRatio;
  }

  public RootResponse _50DayMovingAverage(String _50DayMovingAverage) {
    this._50DayMovingAverage = _50DayMovingAverage;
    return this;
  }

   /**
   * Get _50DayMovingAverage
   * @return _50DayMovingAverage
  **/
  public String get50DayMovingAverage() {
    return _50DayMovingAverage;
  }

  public void set50DayMovingAverage(String _50DayMovingAverage) {
    this._50DayMovingAverage = _50DayMovingAverage;
  }

  public RootResponse _52WeekHigh(String _52WeekHigh) {
    this._52WeekHigh = _52WeekHigh;
    return this;
  }

   /**
   * Get _52WeekHigh
   * @return _52WeekHigh
  **/
  public String get52WeekHigh() {
    return _52WeekHigh;
  }

  public void set52WeekHigh(String _52WeekHigh) {
    this._52WeekHigh = _52WeekHigh;
  }

  public RootResponse ReturnOnEquityTTM(String ReturnOnEquityTTM) {
    this.ReturnOnEquityTTM = ReturnOnEquityTTM;
    return this;
  }

   /**
   * Get ReturnOnEquityTTM
   * @return ReturnOnEquityTTM
  **/
  public String getReturnOnEquityTTM() {
    return ReturnOnEquityTTM;
  }

  public void setReturnOnEquityTTM(String ReturnOnEquityTTM) {
    this.ReturnOnEquityTTM = ReturnOnEquityTTM;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.Description, RootResponse.Description) &&
        Objects.equals(this.Address, RootResponse.Address) &&
        Objects.equals(this._200DayMovingAverage, RootResponse._200DayMovingAverage) &&
        Objects.equals(this.Symbol, RootResponse.Symbol) &&
        Objects.equals(this.EBITDA, RootResponse.EBITDA) &&
        Objects.equals(this.EPS, RootResponse.EPS) &&
        Objects.equals(this.ExDividendDate, RootResponse.ExDividendDate) &&
        Objects.equals(this.Name, RootResponse.Name) &&
        Objects.equals(this.Beta, RootResponse.Beta) &&
        Objects.equals(this.Industry, RootResponse.Industry) &&
        Objects.equals(this.FiscalYearEnd, RootResponse.FiscalYearEnd) &&
        Objects.equals(this.DividendYield, RootResponse.DividendYield) &&
        Objects.equals(this.evToEBITDA, RootResponse.evToEBITDA) &&
        Objects.equals(this.AnalystTargetPrice, RootResponse.AnalystTargetPrice) &&
        Objects.equals(this.Currency, RootResponse.Currency) &&
        Objects.equals(this.DividendDate, RootResponse.DividendDate) &&
        Objects.equals(this.PriceToSalesRatioTTM, RootResponse.PriceToSalesRatioTTM) &&
        Objects.equals(this.evToRevenue, RootResponse.evToRevenue) &&
        Objects.equals(this._52WeekLow, RootResponse._52WeekLow) &&
        Objects.equals(this.GrossProfitTTM, RootResponse.GrossProfitTTM) &&
        Objects.equals(this.DilutedEPSTTM, RootResponse.DilutedEPSTTM) &&
        Objects.equals(this.QuarterlyEarningsGrowthYOY, RootResponse.QuarterlyEarningsGrowthYOY) &&
        Objects.equals(this.CIK, RootResponse.CIK) &&
        Objects.equals(this.OperatingMarginTTM, RootResponse.OperatingMarginTTM) &&
        Objects.equals(this.ProfitMargin, RootResponse.ProfitMargin) &&
        Objects.equals(this.Sector, RootResponse.Sector) &&
        Objects.equals(this.ForwardPE, RootResponse.ForwardPE) &&
        Objects.equals(this.LatestQuarter, RootResponse.LatestQuarter) &&
        Objects.equals(this.TrailingPE, RootResponse.TrailingPE) &&
        Objects.equals(this.RevenueTTM, RootResponse.RevenueTTM) &&
        Objects.equals(this.DividendPerShare, RootResponse.DividendPerShare) &&
        Objects.equals(this.RevenuePerShareTTM, RootResponse.RevenuePerShareTTM) &&
        Objects.equals(this.QuarterlyRevenueGrowthYOY, RootResponse.QuarterlyRevenueGrowthYOY) &&
        Objects.equals(this.ReturnOnAssetsTTM, RootResponse.ReturnOnAssetsTTM) &&
        Objects.equals(this.Exchange, RootResponse.Exchange) &&
        Objects.equals(this.AssetType, RootResponse.AssetType) &&
        Objects.equals(this.BookValue, RootResponse.BookValue) &&
        Objects.equals(this.peRatio, RootResponse.peRatio) &&
        Objects.equals(this.PriceToBookRatio, RootResponse.PriceToBookRatio) &&
        Objects.equals(this.SharesOutstanding, RootResponse.SharesOutstanding) &&
        Objects.equals(this.Country, RootResponse.Country) &&
        Objects.equals(this.MarketCapitalization, RootResponse.MarketCapitalization) &&
        Objects.equals(this.peGRatio, RootResponse.peGRatio) &&
        Objects.equals(this._50DayMovingAverage, RootResponse._50DayMovingAverage) &&
        Objects.equals(this._52WeekHigh, RootResponse._52WeekHigh) &&
        Objects.equals(this.ReturnOnEquityTTM, RootResponse.ReturnOnEquityTTM);
  }

  @Override
  public int hashCode() {
    return Objects.hash(Description, Address, _200DayMovingAverage, Symbol, EBITDA, EPS, ExDividendDate, Name, Beta, Industry, FiscalYearEnd, DividendYield, evToEBITDA, AnalystTargetPrice, Currency, DividendDate, PriceToSalesRatioTTM, evToRevenue, _52WeekLow, GrossProfitTTM, DilutedEPSTTM, QuarterlyEarningsGrowthYOY, CIK, OperatingMarginTTM, ProfitMargin, Sector, ForwardPE, LatestQuarter, TrailingPE, RevenueTTM, DividendPerShare, RevenuePerShareTTM, QuarterlyRevenueGrowthYOY, ReturnOnAssetsTTM, Exchange, AssetType, BookValue, peRatio, PriceToBookRatio, SharesOutstanding, Country, MarketCapitalization, peGRatio, _50DayMovingAverage, _52WeekHigh, ReturnOnEquityTTM);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    Description: ").append(toIndentedString(Description)).append("\n");
    sb.append("    Address: ").append(toIndentedString(Address)).append("\n");
    sb.append("    _200DayMovingAverage: ").append(toIndentedString(_200DayMovingAverage)).append("\n");
    sb.append("    Symbol: ").append(toIndentedString(Symbol)).append("\n");
    sb.append("    EBITDA: ").append(toIndentedString(EBITDA)).append("\n");
    sb.append("    EPS: ").append(toIndentedString(EPS)).append("\n");
    sb.append("    ExDividendDate: ").append(toIndentedString(ExDividendDate)).append("\n");
    sb.append("    Name: ").append(toIndentedString(Name)).append("\n");
    sb.append("    Beta: ").append(toIndentedString(Beta)).append("\n");
    sb.append("    Industry: ").append(toIndentedString(Industry)).append("\n");
    sb.append("    FiscalYearEnd: ").append(toIndentedString(FiscalYearEnd)).append("\n");
    sb.append("    DividendYield: ").append(toIndentedString(DividendYield)).append("\n");
    sb.append("    evToEBITDA: ").append(toIndentedString(evToEBITDA)).append("\n");
    sb.append("    AnalystTargetPrice: ").append(toIndentedString(AnalystTargetPrice)).append("\n");
    sb.append("    Currency: ").append(toIndentedString(Currency)).append("\n");
    sb.append("    DividendDate: ").append(toIndentedString(DividendDate)).append("\n");
    sb.append("    PriceToSalesRatioTTM: ").append(toIndentedString(PriceToSalesRatioTTM)).append("\n");
    sb.append("    evToRevenue: ").append(toIndentedString(evToRevenue)).append("\n");
    sb.append("    _52WeekLow: ").append(toIndentedString(_52WeekLow)).append("\n");
    sb.append("    GrossProfitTTM: ").append(toIndentedString(GrossProfitTTM)).append("\n");
    sb.append("    DilutedEPSTTM: ").append(toIndentedString(DilutedEPSTTM)).append("\n");
    sb.append("    QuarterlyEarningsGrowthYOY: ").append(toIndentedString(QuarterlyEarningsGrowthYOY)).append("\n");
    sb.append("    CIK: ").append(toIndentedString(CIK)).append("\n");
    sb.append("    OperatingMarginTTM: ").append(toIndentedString(OperatingMarginTTM)).append("\n");
    sb.append("    ProfitMargin: ").append(toIndentedString(ProfitMargin)).append("\n");
    sb.append("    Sector: ").append(toIndentedString(Sector)).append("\n");
    sb.append("    ForwardPE: ").append(toIndentedString(ForwardPE)).append("\n");
    sb.append("    LatestQuarter: ").append(toIndentedString(LatestQuarter)).append("\n");
    sb.append("    TrailingPE: ").append(toIndentedString(TrailingPE)).append("\n");
    sb.append("    RevenueTTM: ").append(toIndentedString(RevenueTTM)).append("\n");
    sb.append("    DividendPerShare: ").append(toIndentedString(DividendPerShare)).append("\n");
    sb.append("    RevenuePerShareTTM: ").append(toIndentedString(RevenuePerShareTTM)).append("\n");
    sb.append("    QuarterlyRevenueGrowthYOY: ").append(toIndentedString(QuarterlyRevenueGrowthYOY)).append("\n");
    sb.append("    ReturnOnAssetsTTM: ").append(toIndentedString(ReturnOnAssetsTTM)).append("\n");
    sb.append("    Exchange: ").append(toIndentedString(Exchange)).append("\n");
    sb.append("    AssetType: ").append(toIndentedString(AssetType)).append("\n");
    sb.append("    BookValue: ").append(toIndentedString(BookValue)).append("\n");
    sb.append("    peRatio: ").append(toIndentedString(peRatio)).append("\n");
    sb.append("    PriceToBookRatio: ").append(toIndentedString(PriceToBookRatio)).append("\n");
    sb.append("    SharesOutstanding: ").append(toIndentedString(SharesOutstanding)).append("\n");
    sb.append("    Country: ").append(toIndentedString(Country)).append("\n");
    sb.append("    MarketCapitalization: ").append(toIndentedString(MarketCapitalization)).append("\n");
    sb.append("    peGRatio: ").append(toIndentedString(peGRatio)).append("\n");
    sb.append("    _50DayMovingAverage: ").append(toIndentedString(_50DayMovingAverage)).append("\n");
    sb.append("    _52WeekHigh: ").append(toIndentedString(_52WeekHigh)).append("\n");
    sb.append("    ReturnOnEquityTTM: ").append(toIndentedString(ReturnOnEquityTTM)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
