/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stocks_laboratory.NASDAQstockPrice.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * RootResponse
 */

public class RootResponse {
  @JsonProperty("change_point")
  private Double change_point = null;

  @JsonProperty("change_percentage")
  private Double change_percentage = null;

  @JsonProperty("total_vol")
  private String total_vol = null;

  @JsonProperty("price")
  private Double price = null;

  public RootResponse change_point(Double change_point) {
    this.change_point = change_point;
    return this;
  }

   /**
   * Get change_point
   * @return change_point
  **/
  public Double getChangePoint() {
    return change_point;
  }

  public void setChangePoint(Double change_point) {
    this.change_point = change_point;
  }

  public RootResponse change_percentage(Double change_percentage) {
    this.change_percentage = change_percentage;
    return this;
  }

   /**
   * Get change_percentage
   * @return change_percentage
  **/
  public Double getChangePercentage() {
    return change_percentage;
  }

  public void setChangePercentage(Double change_percentage) {
    this.change_percentage = change_percentage;
  }

  public RootResponse total_vol(String total_vol) {
    this.total_vol = total_vol;
    return this;
  }

   /**
   * Get total_vol
   * @return total_vol
  **/
  public String getTotalVol() {
    return total_vol;
  }

  public void setTotalVol(String total_vol) {
    this.total_vol = total_vol;
  }

  public RootResponse price(Double price) {
    this.price = price;
    return this;
  }

   /**
   * Get price
   * @return price
  **/
  public Double getPrice() {
    return price;
  }

  public void setPrice(Double price) {
    this.price = price;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    RootResponse RootResponse = (RootResponse) o;
    return Objects.equals(this.change_point, RootResponse.change_point) &&
        Objects.equals(this.change_percentage, RootResponse.change_percentage) &&
        Objects.equals(this.total_vol, RootResponse.total_vol) &&
        Objects.equals(this.price, RootResponse.price);
  }

  @Override
  public int hashCode() {
    return Objects.hash(change_point, change_percentage, total_vol, price);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class RootResponse {\n");
    
    sb.append("    change_point: ").append(toIndentedString(change_point)).append("\n");
    sb.append("    change_percentage: ").append(toIndentedString(change_percentage)).append("\n");
    sb.append("    total_vol: ").append(toIndentedString(total_vol)).append("\n");
    sb.append("    price: ").append(toIndentedString(price)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
