/*
 * 
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 2.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package com.stocks_laboratory.twelvedata3.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonValue;
/**
 * ResponseDataEntryItem
 */

public class ResponseDataEntryItem {
  @JsonProperty("symbol")
  private String symbol = null;

  @JsonProperty("country")
  private String country = null;

  @JsonProperty("mic_code")
  private String mic_code = null;

  @JsonProperty("name")
  private String name = null;

  @JsonProperty("currency")
  private String currency = null;

  @JsonProperty("exchange")
  private String exchange = null;

  @JsonProperty("type")
  private String type = null;

  public ResponseDataEntryItem symbol(String symbol) {
    this.symbol = symbol;
    return this;
  }

   /**
   * Get symbol
   * @return symbol
  **/
  public String getSymbol() {
    return symbol;
  }

  public void setSymbol(String symbol) {
    this.symbol = symbol;
  }

  public ResponseDataEntryItem country(String country) {
    this.country = country;
    return this;
  }

   /**
   * Get country
   * @return country
  **/
  public String getCountry() {
    return country;
  }

  public void setCountry(String country) {
    this.country = country;
  }

  public ResponseDataEntryItem mic_code(String mic_code) {
    this.mic_code = mic_code;
    return this;
  }

   /**
   * Get mic_code
   * @return mic_code
  **/
  public String getMicCode() {
    return mic_code;
  }

  public void setMicCode(String mic_code) {
    this.mic_code = mic_code;
  }

  public ResponseDataEntryItem name(String name) {
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public ResponseDataEntryItem currency(String currency) {
    this.currency = currency;
    return this;
  }

   /**
   * Get currency
   * @return currency
  **/
  public String getCurrency() {
    return currency;
  }

  public void setCurrency(String currency) {
    this.currency = currency;
  }

  public ResponseDataEntryItem exchange(String exchange) {
    this.exchange = exchange;
    return this;
  }

   /**
   * Get exchange
   * @return exchange
  **/
  public String getExchange() {
    return exchange;
  }

  public void setExchange(String exchange) {
    this.exchange = exchange;
  }

  public ResponseDataEntryItem type(String type) {
    this.type = type;
    return this;
  }

   /**
   * Get type
   * @return type
  **/
  public String getType() {
    return type;
  }

  public void setType(String type) {
    this.type = type;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ResponseDataEntryItem Response_dataEntryItem = (ResponseDataEntryItem) o;
    return Objects.equals(this.symbol, Response_dataEntryItem.symbol) &&
        Objects.equals(this.country, Response_dataEntryItem.country) &&
        Objects.equals(this.mic_code, Response_dataEntryItem.mic_code) &&
        Objects.equals(this.name, Response_dataEntryItem.name) &&
        Objects.equals(this.currency, Response_dataEntryItem.currency) &&
        Objects.equals(this.exchange, Response_dataEntryItem.exchange) &&
        Objects.equals(this.type, Response_dataEntryItem.type);
  }

  @Override
  public int hashCode() {
    return Objects.hash(symbol, country, mic_code, name, currency, exchange, type);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ResponseDataEntryItem {\n");
    
    sb.append("    symbol: ").append(toIndentedString(symbol)).append("\n");
    sb.append("    country: ").append(toIndentedString(country)).append("\n");
    sb.append("    mic_code: ").append(toIndentedString(mic_code)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    currency: ").append(toIndentedString(currency)).append("\n");
    sb.append("    exchange: ").append(toIndentedString(exchange)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}
